apiVersion: v1
kind: Service
metadata:
  name: jain-dharamshaala-service
spec:
  selector:
    app: jain-dharamshaala
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer